image: alpine/latest
secrets:
  - 5fd6bbf1-8791-4c37-8e1f-2d423d1c6a12
environment:
  GH_REPO: srht-socio
  GH_USER: rogeruiz
  SH_REPO: socio
tasks:
  - mirror-to-github: |
      cd ~/"${SH_REPO}"
      git config --global credential.helper store
      git push --mirror "https://github.com/${GH_USER}/${GH_REPO}"
